FROM amazon/aws-lambda-python:3.7

# the terraform-aws-lambda module will mount the lambda sources into this directory
# and expect it to be the CWD when calling `docker run`
WORKDIR /var/task
ENTRYPOINT [""]
